title: Rivaldi-Blog
description: "A Journey of Software Craftman from Gorontalo"
author:
  name: "Rivaldi"
  email: "cbot59@gmail.com"
  url: "https://rivaldi.dev"

baseurl: /

source: .
destination: ./_site
permalink: pretty
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Rivaldi"
year : "2019"
